CREATE OR REPLACE PACKAGE "OW_TST_US"."AUTENTICACION_USUARIO" AS

  PROCEDURE AUTENTICACION(
            P_DOCUMENTO  USUARIOS.DOCUMENTO%TYPE,
            P_NOMBRE    USUARIOS.NOMBRE%TYPE
  );

END AUTENTICACION_USUARIO;

 /

prompt
prompt PACKAGE BODY: AUTENTICACION_USUARIO
prompt

create or replace PACKAGE BODY AUTENTICACION_USUARIO AS
--
  PROCEDURE AUTENTICACION(
            P_DOCUMENTO  USUARIOS.DOCUMENTO%TYPE,
            P_NOMBRE    USUARIOS.NOMBRE%TYPE
            
  ) IS
		V_NOMBRE NVARCHAR2(100);
    BEGIN
			SELECT NOMBRE INTO V_NOMBRE FROM USUARIOS WHERE DOCUMENTO = P_DOCUMENTO AND NOMBRE = P_NOMBRE;
			dbms_output.put_line('CLAVE CORRECTA BIENVENIDO(A) : '||V_NOMBRE);
			EXCEPTION
			WHEN OTHERS THEN
			dbms_output.put_line('CLAVE O NOMBRE INCORRECTA');
			
	END ;

END AUTENTICACION_USUARIO;