--------------------------------------------------------
-- Archivo creado  - viernes-marzo-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "OW_TST_US"."USUARIOS" 
   (	"DOCUMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"APELLIDOS" VARCHAR2(255 BYTE), 
	"EDAD" NUMBER(*,0), 
	"SALARIO" NUMBER(*,0), 
	"FECHA_DE_INGRESO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTST" ;
REM INSERTING into OW_TST_US.USUARIOS
SET DEFINE OFF;
Insert into OW_TST_US.USUARIOS (DOCUMENTO,NOMBRE,APELLIDOS,EDAD,SALARIO,FECHA_DE_INGRESO) values ('123456789','JOAN','TORRES','25','800000',to_date('03/05/03','DD/MM/RR'));
Insert into OW_TST_US.USUARIOS (DOCUMENTO,NOMBRE,APELLIDOS,EDAD,SALARIO,FECHA_DE_INGRESO) values ('1018480669','JHOSUE','CRACK','23','484645',to_date('03/05/14','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PK_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "OW_TST_US"."PK_USUARIOS" ON "OW_TST_US"."USUARIOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTST" ;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "OW_TST_US"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTST"  ENABLE;
  ALTER TABLE "OW_TST_US"."USUARIOS" MODIFY ("FECHA_DE_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "OW_TST_US"."USUARIOS" MODIFY ("SALARIO" NOT NULL ENABLE);
  ALTER TABLE "OW_TST_US"."USUARIOS" MODIFY ("EDAD" NOT NULL ENABLE);
  ALTER TABLE "OW_TST_US"."USUARIOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
